development:
  adapter: postgresql
  encoding: unicode
  database: bdns_hosts_development
  pool: 5
  username: user
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: bdns_hosts_test
  pool: 5
  username: user
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: bdns_hosts_production
  pool: 5
  username: user
  password:
